version: 0.5.{build}
image: Visual Studio 2017

build:
  verbosity: minimal

branches:
  only:
  - master

init:
- cmd: choco install dotnetcore-sdk --version 3.0.100-preview5-011568
- git config --global core.autocrlf input

build_script:
- ps: dotnet publish src/Bolero.TodoMVC.Client/ -o $pwd/publish/

on_success:
- ps: .\tools\gh-pages.ps1 -env appveyor

environment:
  GH_TOKEN:
    secure: dhFy1eZoqG4QPkKTuLFxix7QQMxaIyIpYjkvTU3CukYZz1CEOJeHfBSaT8tkPsGL
